### ISSUE TITLE
Germany

### ISSUE THREAD

**Issue by stefanw** [openspending/farmsubsidy-scrapers#10]
- [Data source](http://www.agrar-fischerei-zahlungen.de/Suche)
- Estimated difficulty of extraction: **hard**

Sub-Tasks:

- [x] Assign responsible person
- [ ] Get data via FOI
- [ ] Get latest data

**Comment by stefanw** [comment]
[New data is not relased under FOI](https://fragdenstaat.de/anfrage/empfanger-des-eu-agrarfonds-2014/), I wrote a scraper that I will release soon.

**Comment by cyberbikepunk** [comment]
Where's the scraper @stefanw ? I don't see it in the scrapy folder. If it's not done, I can do it. This one is not that hard.

**Comment by stefanw** [comment]
It's done, I already acquired the 2015 data last week. It's not a scrapy scraper though, that's why it's a bit harder to integrate. The scraper itself is moderately difficult because you have a limit on the result set that you need to handle.

**Comment by stefanw** [comment]
Uploaded the scraper, will push some updated scraping framework code soon.
