### ISSUE TITLE
Croatia

### ISSUE THREAD

**Issue by stefanw** [openspending/farmsubsidy-scrapers#12]
- [Data source](http://isplate.apprrr.hr/)
- Estimated difficulty of extraction: **unknown**

Sub-Tasks:

- [x] Assign responsible person
- [x] Build scraper
- [x] Get latest data

**Comment by cyberbikepunk** [comment]
This is gonna be my first shot.

**Comment by cyberbikepunk** [comment]
I'm just running my HR spider with the latest changes. As soon as everything is in S3 and the results pass the sanity check I'll send a PR.

**Comment by cyberbikepunk** [comment]
Done. The sooner you merge, the better, cause there are a few changes in the settings file that I would like to use in the next spider. thx!

**Comment by stefanw** [comment]
@cyberbikepunk You don't happen to have the 2014 data lying around?
