### ISSUE TITLE
Hungary

### ISSUE THREAD

**Issue by stefanw** [openspending/farmsubsidy-scrapers#13]
- [Data source](https://www.mvh.gov.hu/-/tamogatasi-adatok-a-bizottsag-908-2014-eu-vegrehajtasi-rendelete-alapjan-publication-of-data-according-to-commission-implementing-regulation-no-908-20)
- Estimated difficulty of extraction: **easy**

Sub-Tasks:

- [ ] Assign responsible person
- [ ] Build scraper
- [ ] Get latest data

**Comment by cyberbikepunk** [comment]
I can't find anything to scrape. It looks like the data needs to be requested.

**Comment by stefanw** [comment]
Sorry, the link in the issue wasn't out of date. [I updated it to this link.](https://www.mvh.gov.hu/-/tamogatasi-adatok-a-bizottsag-908-2014-eu-vegrehajtasi-rendelete-alapjan-publication-of-data-according-to-commission-implementing-regulation-no-908-20)

**Comment by cyberbikepunk** [comment]
okay, old school design but really great for scraping

**Comment by cyberbikepunk** [comment]
This is the site that provides the most complete info that i ve seen so far. well done
