### ISSUE TITLE
Latvia

### ISSUE THREAD

**Issue by stefanw** [openspending/farmsubsidy-scrapers#16]
- [Data source](https://eps.lad.gov.lv/payment_recipients/index)
- Estimated difficulty of extraction: **easy**

Sub-Tasks:

- [x] Assign responsible person
- [x] Write a small script to download and agglomerate CSV files
- [x] Get latest data

**Comment by cyberbikepunk** [comment]
This site lets you download a CSV over [this link](https://eps.lad.gov.lv/payment_recipients?commit=Mekl%C4%93t&eps_payment%5Bdisplay_name%5D=&eps_payment%5Bdistrict%5D=&eps_payment%5Bfund%5D=elf&eps_payment%5Bschema%5D=&eps_payment%5Bsum_from%5D=&eps_payment%5Bsum_to%5D=&eps_payment%5Btax_payer_number%5D=&eps_payment%5Byear%5D=2014&eps_payment%5Byear_type%5D=F&format=csv&utf8=%E2%9C%93). Except the request takes forever

**Comment by cyberbikepunk** [comment]
Asking for all the data at once just doesn't work, The requests has to be broken up by funding scheme. I'm gonna write a small script.

**Comment by cyberbikepunk** [comment]
Unfortunately the data doesn't distinguish between the EADS and EADFS agencies. And the data for 2015 is not yet available.

**Comment by cyberbikepunk** [comment]
The csv dump is on S3. One concern is that I use a slugified version of the recipient name as the recipient id. Probably not enough to ensure that it's unique.
