### ISSUE TITLE
Lithuania

### ISSUE THREAD

**Issue by stefanw** [openspending/farmsubsidy-scrapers#17]
- [Data source](https://portal.nma.lt/portal/page/portal/NMA%20Pages/fas_search)
- Estimated difficulty of extraction: **easy**

Sub-Tasks:
- [x] Assign responsible person
- [x] Build scraper
- [x] Get latest data

**Comment by cyberbikepunk** [comment]
Okay so I warmed up with Croatia. Let's try another low hanging fruit.

**Comment by cyberbikepunk** [comment]
See the comment in the PR about some ambiguity the way that I scrape the EADS subsidies,

**Comment by cyberbikepunk** [comment]
Spiders are currently crawling. I'm closing this.

**Comment by stefanw** [comment]
Does not seem to work for 2016 out of the box.

**Comment by stefanw** [comment]
Tried to fix the scrapy spider, but ended up writing a scraper notebook that got the data.
